"""Checked-in English-corpus failure traces for the local visual lab.

These are immutable teaching artifacts distilled from the reproducible failure
fixtures.  They are not generated by the browser, so a learner can compare a
baseline and intervention offline while inspecting the actual evidence,
context decision, answer/citation state, and observed failure label.
"""


def _trace(*, evidence, selected, omitted, answer, citations, label):
    return {
        "evidence": evidence,
        "context_pack": {"selected": selected, "omitted": omitted},
        "answer": answer,
        "citations": citations,
        "outcome_label": label,
    }


FAILURE_LESSONS = [
    {
        "id": "missing-evidence", "label": "missing_evidence",
        "question": "What topics does the sample document cover?",
        "explanation": {
            "en": "A narrow candidate set can omit the only supporting document.",
            "zh": "候选集合过小，可能遗漏唯一能够提供支持的文档。",
        },
        "baseline": {
            "config": {"retriever": "dense", "top_k": 1},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.81, "doc_id": "section_alpha.md", "text": "Alpha section fixture text."}],
                selected=["section-alpha"], omitted=[], answer="I cannot support an answer from the retrieved context.", citations=[], label="missing_evidence",
            ),
        },
        "intervention": {
            "config": {"retriever": "dense", "top_k": 6},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.91, "doc_id": "with_h1.md", "text": "Sample document with its supported topics."}],
                selected=["with-h1"], omitted=[], answer="The sample document covers the topics stated in its text.", citations=["with_h1.md"], label="no_failure",
            ),
        },
    },
    {
        "id": "distractor-evidence", "label": "distractor_evidence",
        "question": "What does the plain text document say about its title?",
        "explanation": {
            "en": "Too many candidates add unrelated context that competes with the evidence.",
            "zh": "过多候选会加入无关上下文，与真正证据相互干扰。",
        },
        "baseline": {
            "config": {"retriever": "dense", "top_k": 6},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.74, "doc_id": "section_beta.md", "text": "Unrelated beta section."}, {"rank": 3, "score": 0.62, "doc_id": "plain.txt", "text": "Plain text document title evidence."}],
                selected=["section-beta", "plain"], omitted=[], answer="The title is difficult to identify among unrelated context.", citations=[], label="distractor_evidence",
            ),
        },
        "intervention": {
            "config": {"retriever": "dense", "top_k": 2},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.82, "doc_id": "plain.txt", "text": "Plain text document title evidence."}],
                selected=["plain"], omitted=[], answer="The plain text document states its title directly.", citations=["plain.txt"], label="no_failure",
            ),
        },
    },
    {
        "id": "unsupported-answer", "label": "unsupported_answer",
        "question": "What topics does the sample document cover?",
        "explanation": {
            "en": "Retrieved evidence can be correct while an answer still invents unsupported claims.",
            "zh": "即使检索证据正确，答案仍可能编造没有证据支持的内容。",
        },
        "baseline": {
            "config": {"retriever": "dense", "top_k": 3},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.91, "doc_id": "with_h1.md", "text": "Sample corpus topic description."}],
                selected=["with-h1"], omitted=[], answer="The document covers Roman history and medieval castles.", citations=[], label="unsupported_answer",
            ),
        },
        "intervention": {
            "config": {"retriever": "dense", "top_k": 3},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.91, "doc_id": "with_h1.md", "text": "Sample corpus topic description."}],
                selected=["with-h1"], omitted=[], answer="The document covers the topics described in the sample corpus.", citations=["with_h1.md"], label="no_failure",
            ),
        },
    },
    {
        "id": "citation-mismatch", "label": "citation_mismatch",
        "question": "Where does the nested document live?",
        "explanation": {
            "en": "A citation must point to the source that supports the specific claim.",
            "zh": "引用必须指向能够支持该具体断言的来源。",
        },
        "baseline": {
            "config": {"retriever": "dense", "top_k": 3},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.77, "doc_id": "subdir/nested.md", "text": "Nested document is in a subdirectory."}],
                selected=["nested"], omitted=[], answer="The nested document lives in the root directory [Source: with_h1.md].", citations=["with_h1.md"], label="citation_mismatch",
            ),
        },
        "intervention": {
            "config": {"retriever": "dense", "top_k": 3},
            "trace": _trace(
                evidence=[{"rank": 1, "score": 0.77, "doc_id": "subdir/nested.md", "text": "Nested document is in a subdirectory."}],
                selected=["nested"], omitted=[], answer="The nested document lives in a subdirectory [Source: subdir/nested.md].", citations=["subdir/nested.md"], label="no_failure",
            ),
        },
    },
]
