import type { Area, Lang } from "./types";

export const copy = {
  en: {
    title: "tiny-rag-lab",
    subtitle: "See classic RAG, step by step.",
    areas: { home: "Home", build: "Build & Inspect", explore: "Explore", failure: "Failure Lab", settings: "Settings" } satisfies Record<Area, string>,
    buildViews: { build: "Build index", inspect: "Inspect index" },
    upload: "Add Markdown or text files", build: "Build index", question: "Ask a question", retrieve: "Retrieve", ask: "Live ask",
    noIndex: "Build an index, or replay the starter trace, to begin exploring.",
    stages: ["Corpus", "Chunks", "Embeddings", "Retrieve", "Context", "Answer"],
    stageBriefs: [
      "The source corpus and the index facts used for this run.",
      "The text pieces that can become retrieval evidence.",
      "A small preview of the query vector used for search.",
      "Ranked evidence returned by the selected retriever.",
      "Evidence chosen for the grounded prompt within the budget.",
      "The generated response and the citations returned with it.",
    ],
    evidence: "Evidence", prompt: "Grounded prompt", answer: "Answer", vectors: "Vector preview", manifest: "Index manifest",
    provider: "Live ask needs an OpenAI-compatible provider configured for this local lab.",
    quick: "Replay a saved run first, then build a small index when you are ready to explore with your own question.",
    replay: "Replay starter trace", watson: "Download watsonxDocsQA", backend: "Vector index backend", index: "Index",
    providerUrl: "Provider base URL", providerModel: "Model", providerKey: "API key (this session only)",
    modelReady: "Default embedding model is ready", modelMissing: "Download the default embedding model before building a custom index", downloadModel: "Download default embedding model",
    retriever: "Retriever", topK: "Top-k", contextBudget: "Context budget (0 = unlimited)",
    selected: "Selected for context", omitted: "Not selected for context", vector: "Query vector", timings: "Stage timings",
    baseline: "Baseline", intervention: "Intervention", learn: "Read the learning material", raw: "Inspect raw artifact", source: "Source", score: "Score",
    scoreDetails: "Score details", citations: "Citations returned", indexFacts: "Index facts", chunks: "Chunks", documents: "Documents", embeddingModel: "Embedding model",
    buildIntro: "Bring a small corpus into the lab, choose its local vector backend, and build an inspectable index.",
    inspectIntro: "Review the saved index facts, chunks, and a numeric vector preview without leaving the lab.",
    exploreIntro: "Run retrieval or a live grounded answer, then follow the same artifacts through each pipeline stage.",
    failureIntro: "Compare a known failure with an intervention using the project’s curated trace artifacts.",
    settingsIntro: "Configure the local embedding model and an optional OpenAI-compatible provider.",
    replayDetail: "Saved offline trace · no model download or provider required.",
    buildPath: "Build a small index", buildPathDetail: "Upload a small corpus, inspect its chunks, then ask your own question.",
    rawVector: "First 8 dimensions only — these values are a numeric preview, not human-readable concepts.",
    qdrantOptional: "Qdrant (optional)", embeddingSettings: "Embedding model", providerSettings: "OpenAI-compatible provider", runConfiguration: "Run configuration",
    corpusAdded: "Corpus added.", indexing: "Indexing locally…", indexReady: "Index ready.", watsonStatus: "watsonxDocsQA", myCorpus: "My corpus",
    retrieverOptions: { dense: "Dense", bm25: "BM25", hybrid: "Hybrid (RRF)" },
  },
  zh: {
    title: "tiny-rag-lab",
    subtitle: "循序看见经典 RAG 如何工作。",
    areas: { home: "主页", build: "构建与检查", explore: "探索", failure: "失败实验室", settings: "设置" } satisfies Record<Area, string>,
    buildViews: { build: "构建索引", inspect: "检查索引" },
    upload: "添加 Markdown 或文本文件", build: "构建索引", question: "输入问题", retrieve: "检索", ask: "实时问答",
    noIndex: "构建一个索引，或回放入门 trace 后，即可开始探索。",
    stages: ["语料", "分块", "嵌入", "检索", "上下文", "答案"],
    stageBriefs: [
      "本次运行使用的源语料与索引事实。",
      "可以成为检索证据的文本片段。",
      "用于搜索的查询向量简要预览。",
      "由所选检索器返回的已排序证据。",
      "在预算内被选入基于证据提示词的片段。",
      "生成的回答，以及随回答返回的引用。",
    ],
    evidence: "证据", prompt: "基于证据的提示词", answer: "答案", vectors: "向量预览", manifest: "索引清单",
    provider: "实时问答需要为本地实验室配置 OpenAI 兼容的模型服务。",
    quick: "先回放一次已保存的运行，再构建一个小型索引，用自己的问题探索。",
    replay: "回放入门 trace", watson: "下载 watsonxDocsQA", backend: "向量索引后端", index: "索引",
    providerUrl: "模型服务地址", providerModel: "模型", providerKey: "API 密钥（仅当前会话）",
    modelReady: "默认嵌入模型已就绪", modelMissing: "构建自定义索引前需要下载默认嵌入模型", downloadModel: "下载默认嵌入模型",
    retriever: "检索器", topK: "Top-k", contextBudget: "上下文预算（0 = 不限）", selected: "已选入上下文", omitted: "未选入上下文", vector: "查询向量", timings: "阶段耗时",
    baseline: "基线", intervention: "干预", learn: "阅读学习材料", raw: "查看原始产物", source: "来源", score: "分数",
    scoreDetails: "分数详情", citations: "返回的引用", indexFacts: "索引事实", chunks: "分块", documents: "文档", embeddingModel: "嵌入模型",
    buildIntro: "把一个小型语料库带入实验室，选择本地向量后端，并构建可检查的索引。",
    inspectIntro: "无需离开实验室，即可检查已保存的索引事实、分块和数值化向量预览。",
    exploreIntro: "运行检索或实时的基于证据问答，并沿着每个管道阶段查看同一批产物。",
    failureIntro: "使用项目精心设计的 trace 产物，对比一个已知失败案例和干预措施。",
    settingsIntro: "配置本地嵌入模型，以及可选的 OpenAI 兼容模型服务。",
    replayDetail: "已保存的离线 trace · 无需下载模型或配置模型服务。",
    buildPath: "构建小型索引", buildPathDetail: "上传一个小型语料库，检查它的分块，再提出自己的问题。",
    rawVector: "仅显示前 8 个维度——这些数值是预览，不对应人类可读的概念。",
    qdrantOptional: "Qdrant（可选）", embeddingSettings: "嵌入模型", providerSettings: "OpenAI 兼容模型服务", runConfiguration: "运行配置",
    corpusAdded: "已添加语料库。", indexing: "正在本地构建索引…", indexReady: "索引已就绪。", watsonStatus: "watsonxDocsQA", myCorpus: "我的语料库",
    retrieverOptions: { dense: "语义检索", bm25: "BM25", hybrid: "混合（RRF）" },
  },
} as const;

export type Copy = (typeof copy)[Lang];

export function learningMaterialUrl(lang: Lang, page: string) {
  return `https://github.com/jameswei/tiny-rag-lab/blob/main/learning_materials/${lang}/${page}`;
}
