import type { Area, Lang } from "./types";

export const copy = {
  en: {
    title: "tiny-rag-lab",
    subtitle: "See classic RAG, step by step.",
    areas: { home: "Home", learn: "Learn", build: "Build & Inspect", explore: "Explore", failure: "Failure Lab", settings: "Settings" } satisfies Record<Area, string>,
    buildViews: { build: "Build index", inspect: "Inspect index" },
    upload: "Add Markdown or text files", build: "Build index", question: "Ask a question", retrieve: "Retrieve", retrieving: "Retrieving…", ask: "Live ask", testing: "Testing connection…", generating: "Generating answer…", testConnection: "Test connection",
    noIndex: "Choose an index to begin exploring.",
    stages: ["Corpus", "Chunks", "Embeddings", "Retrieve", "Context", "Answer"],
    whatToNotice: "What to notice",
    learnStageFocus: [
      "Start with scope: this is the corpus and index behind the lesson.",
      "A document becomes several retrievable chunks; compare their source and text.",
      "These values are coordinates, not words. Search compares their direction and distance.",
      "Inspect the ranked candidates: related text is not always useful evidence.",
      "Compare selected and omitted chunks. Only selected evidence reaches the prompt.",
      "Read the answer with its cited sources, then match each citation to the evidence below.",
    ],
    evidence: "Evidence", prompt: "Grounded prompt", answer: "Answer", vectors: "Vector preview", manifest: "Index manifest",
    provider: "Live ask needs an OpenAI-compatible provider configured for this local lab.", providerTestHint: "Verifies this provider before it is used for Live ask.", providerUnlocked: "Live ask is unlocked by your verified provider connection.", generationFailed: "Live generation failed. Check provider settings and try again.", selectedEvidence: "Selected context evidence", abstention: "Grounded abstention", noSupportedAnswer: "No supported answer in this corpus", abstained: "This question is outside the selected corpus’s coverage. The model found no support in its context, so it declined to invent an answer.", showFull: "Show full text", scenarioQuestion: "Question",
    quick: "Follow one complete, recorded RAG lesson first. Then use Explore to run your own retrievals over the same real corpus.",
    replay: "Start guided lesson", watson: "Download watsonxDocsQA", backend: "Vector index backend", index: "Index",
    providerUrl: "Provider API URL", providerModel: "Model", providerKey: "API key (this session only)",
    modelReady: "Default embedding model is ready: all-MiniLM-L6-v2 (384 dimensions)", modelMissing: "Download the default embedding model before building an index", modelDownloadRequired: "Dense and Hybrid retrieval need the default embedding model. Open Settings, download it, then retry.", modelDownloading: "Downloading default embedding model…", modelDownloadInProgress: "Download in progress. This page will update when the model is ready.", downloadModel: "Download default embedding model",
    retriever: "Retriever", topK: "Top-k", contextBudget: "Context budget (0 = unlimited)",
    selected: "Selected for context", omitted: "Not selected for context", vector: "Query vector", timings: "Stage timings",
    baseline: "Baseline", intervention: "Intervention", learn: "Read the learning guide", raw: "Inspect raw artifact", source: "Source", score: "Score", chunkReference: "Chunk ID", citationReference: "Source reference",
    scoreDetails: "Score details", citations: "Sources cited in the answer", indexFacts: "Index facts", chunks: "Chunks", documents: "Documents", embeddingModel: "Embedding model",
    buildIntro: "Start with a bundled corpus or bring a small corpus of your own. Then choose a local vector backend and build an inspectable index.",
    inspectIntro: "Review the saved index facts, chunks, and a numeric vector preview without leaving the lab.",
    exploreIntro: "Run retrieval or a live grounded answer, then follow the same artifacts through each pipeline stage.",
    failureIntro: "Compare a known failure with an intervention using the project’s curated trace artifacts.",
    settingsIntro: "Check the bundled local embedding model and configure an optional OpenAI-compatible provider.",
    replayDetail: "Recorded offline lesson · no model download or provider required.",
    buildPath: "Build a small index", buildPathDetail: "Upload a small corpus, inspect its chunks, then ask your own question.",
    rawVector: "First 8 dimensions only — these values are a numeric preview, not human-readable concepts.",
    bundledCorpus: "Use a bundled corpus", customCorpus: "Bring a small corpus", chooseUploadedCorpus: "Choose an uploaded corpus", noUploadedCorpus: "No uploaded corpus yet", or: "or",
    qdrantReady: "Qdrant — ready", qdrantUnavailable: "Qdrant — unavailable", qdrantUnavailableHint: "Start the optional Qdrant service to use this backend.", embeddingSettings: "Bundled embedding model", providerSettings: "OpenAI-compatible provider", runConfiguration: "Run configuration",
    corpusAdded: "Corpus added.", indexing: "Indexing locally…", indexReady: "Index ready.", watsonStatus: "watsonxDocsQA", myCorpus: "My corpus",
    retrieverOptions: { dense: "Dense", bm25: "BM25", hybrid: "Hybrid (RRF)" },
    learnIntro: "Follow a saved lesson over pinned technical documentation. Each step exposes the actual artifact the RAG system used.", lesson: "Guided lesson", recorded: "Saved teaching result — no live model call", continueLesson: "Continue", loadingLesson: "Loading lesson…", expectedSources: "Expected", retrievedSources: "Retrieved", catalogQuestion: "Catalog question", freeQuestion: "Free question", goldCheck: "Gold-source check", hit: "A gold source was retrieved", miss: "No gold source was retrieved", sourceIdentity: "Pinned source identity",
  },
  zh: {
    title: "tiny-rag-lab",
    subtitle: "循序看见经典 RAG 如何工作。",
    areas: { home: "主页", learn: "学习", build: "构建与检查", explore: "探索", failure: "失败实验室", settings: "设置" } satisfies Record<Area, string>,
    buildViews: { build: "构建索引", inspect: "检查索引" },
    upload: "添加 Markdown 或文本文件", build: "构建索引", question: "输入问题", retrieve: "检索", retrieving: "正在检索…", ask: "实时问答", testing: "正在测试连接…", generating: "正在生成答案…", testConnection: "测试连接",
    noIndex: "选择一个索引后即可开始探索。",
    stages: ["语料", "分块", "嵌入", "检索", "上下文", "答案"],
    whatToNotice: "观察重点",
    learnStageFocus: [
      "先确认范围：这是本课程使用的语料与索引。",
      "一篇文档会变成多个可检索分块；对比它们的来源与文本。",
      "这些数值是坐标，不是词语；搜索比较的是它们的方向与距离。",
      "检查排序后的候选：相关文本不一定是有用的证据。",
      "对比选入与未选入的分块；只有选入的证据会进入提示词。",
      "将答案与其引用来源一起阅读，再把每条引用对应到下方证据。",
    ],
    evidence: "证据", prompt: "基于证据的提示词", answer: "答案", vectors: "向量预览", manifest: "索引清单",
    provider: "实时问答需要为本地实验室配置 OpenAI 兼容的模型服务。", providerTestHint: "先验证模型服务，才能用于实时问答。", providerUnlocked: "已验证的模型服务已解锁实时问答。", generationFailed: "实时生成失败。请检查模型服务设置后重试。", selectedEvidence: "选入上下文的证据", abstention: "基于证据的拒答", noSupportedAnswer: "当前语料中没有可支持的答案", abstained: "这个问题超出了当前所选语料的覆盖范围。模型在上下文中找不到支持证据，因此拒绝编造答案。", showFull: "展开完整文本", scenarioQuestion: "问题",
    quick: "先沿着一次完整、已记录的 RAG 课程学习，再用探索页在同一真实语料上运行自己的检索。",
    replay: "开始引导课程", watson: "下载 watsonxDocsQA", backend: "向量索引后端", index: "索引",
    providerUrl: "模型服务 API 地址", providerModel: "模型", providerKey: "API 密钥（仅当前会话）",
    modelReady: "默认嵌入模型已就绪：all-MiniLM-L6-v2（384 维）", modelMissing: "构建索引前需要下载默认嵌入模型", modelDownloadRequired: "语义检索和混合检索需要默认嵌入模型。请前往设置下载模型后重试。", modelDownloading: "正在下载默认嵌入模型…", modelDownloadInProgress: "下载正在进行中。模型就绪后此页面会自动更新。", downloadModel: "下载默认嵌入模型",
    retriever: "检索器", topK: "Top-k", contextBudget: "上下文预算（0 = 不限）", selected: "已选入上下文", omitted: "未选入上下文", vector: "查询向量", timings: "阶段耗时",
    baseline: "基线", intervention: "干预", learn: "阅读学习指南", raw: "查看原始产物", source: "来源", score: "分数", chunkReference: "分块 ID", citationReference: "来源引用",
    scoreDetails: "分数详情", citations: "答案引用的来源", indexFacts: "索引事实", chunks: "分块", documents: "文档", embeddingModel: "嵌入模型",
    buildIntro: "使用随附的语料库，或带入自己的小型语料库。接着选择本地向量后端，并构建可检查的索引。",
    inspectIntro: "无需离开实验室，即可检查已保存的索引事实、分块和数值化向量预览。",
    exploreIntro: "运行检索或实时的基于证据问答，并沿着每个管道阶段查看同一批产物。",
    failureIntro: "使用项目精心设计的 trace 产物，对比一个已知失败案例和干预措施。",
    settingsIntro: "检查随实验室提供的本地嵌入模型，并配置可选的 OpenAI 兼容模型服务。",
    replayDetail: "已记录的离线课程 · 无需下载模型或配置模型服务。",
    buildPath: "构建小型索引", buildPathDetail: "上传一个小型语料库，检查它的分块，再提出自己的问题。",
    rawVector: "仅显示前 8 个维度——这些数值是预览，不对应人类可读的概念。",
    bundledCorpus: "使用随附的语料库", customCorpus: "带入小型语料库", chooseUploadedCorpus: "选择已上传的语料库", noUploadedCorpus: "尚未上传语料库", or: "或",
    qdrantReady: "Qdrant — 已就绪", qdrantUnavailable: "Qdrant — 不可用", qdrantUnavailableHint: "启动可选的 Qdrant 服务后即可使用此后端。", embeddingSettings: "随附的嵌入模型", providerSettings: "OpenAI 兼容模型服务", runConfiguration: "运行配置",
    corpusAdded: "已添加语料库。", indexing: "正在本地构建索引…", indexReady: "索引已就绪。", watsonStatus: "watsonxDocsQA", myCorpus: "我的语料库",
    retrieverOptions: { dense: "语义检索", bm25: "BM25", hybrid: "混合（RRF）" },
    learnIntro: "沿着一条固定技术文档上的已保存课程学习。每一步都展示 RAG 系统实际使用的产物。", lesson: "引导课程", recorded: "保存的教学结果——未调用实时模型", continueLesson: "继续", loadingLesson: "正在加载课程…", expectedSources: "标准来源", retrievedSources: "检索到的来源", catalogQuestion: "题库问题", freeQuestion: "自由问题", goldCheck: "标准来源检查", hit: "已检索到标准来源", miss: "未检索到标准来源", sourceIdentity: "固定来源标识",
  },
} as const;

export type Copy = (typeof copy)[Lang];

export function learningMaterialUrl(lang: Lang, page: string) {
  return `/docs/${lang}/${page.replace(/\.md$/, ".html")}`;
}
