import type { Area, Lang } from "./types";

export const copy = {
  en: {
    title: "tiny-rag-lab",
    subtitle: "See classic RAG, step by step.",
    areas: { home: "Home", learn: "Learn", retrieval: "Retrieval", build: "Build & Inspect", explore: "Explore", failure: "Failure Lab", settings: "Settings" } satisfies Record<Area, string>,
    retrievalIntro: "Follow a live retrieval result from words to vectors, fusion, reranking, and evaluation. No LLM provider is needed.",
    retrievalModules: {
      lexical: { title: "Lexical", description: "Which query terms earned this BM25 score?" },
      dense: { title: "Dense", description: "How do vectors become cosine similarity?" },
      "vector-db": { title: "Vector database", description: "Move the same vectors from NumPy to Qdrant." },
      hybrid: { title: "Hybrid", description: "Combine lexical and semantic ranks with RRF." },
      reranking: { title: "Reranking", description: "Reorder a broad candidate pool for final relevance." },
      evaluation: { title: "Evaluation", description: "Compare two retrieval configurations over 16 questions." },
    },
    curatedQuestion: "Reviewed question", reviewedSources: "Reviewed source documents", runLesson: "Run live retrieval", runningLesson: "Retrieving and explaining…", questionTokens: "Query tokens", termContributions: "BM25 term contributions", vectorMath: "Cosine calculation", vectorReadingGuide: "Read from the zero line: blue positive values extend upward, coral negative values extend downward, and length shows magnitude within this vector preview.", candidateVector: "Chunk vector", queryNorm: "Query norm", chunkNorm: "Chunk norm", dotProduct: "Dot product", cosine: "Cosine similarity", formula: "Calculation", courseUnavailable: "The reviewed retrieval materials are not installed yet.", moduleComing: "This live module is implemented in the next task of the active milestone.", exactArtifacts: "The values below are returned by the same engine calculation that produced the rank.",
    bm25Meaning: "BM25 adds each query term’s contribution. A term matters more when it appears in this chunk but is uncommon across the corpus; length normalization prevents long chunks from winning only because they contain more words.",
    bm25Formula: "score = Σ query count × IDF × tf(k1 + 1) / (tf + k1(1 − b + b × dl / avgdl))",
    bm25Columns: { term: "Query term", queryCount: "Query count", termFrequency: "Frequency in chunk", documentFrequency: "Chunks containing term", inverseDocumentFrequency: "Inverse document frequency", contribution: "Score contribution", documentLength: "Chunk length", averageDocumentLength: "Average chunk length" },
    rrfFormula: "Each source contributes 1 / ({k} + rank). The fused score is their sum.", rrfMissingSource: "If a chunk is outside one source’s candidate list, that source contributes 0.", notInSourceRanking: "Outside this source’s candidate list", denseRanking: "Dense ranking", lexicalRanking: "BM25 ranking", fusedRanking: "Fused ranking", firstStageCandidates: "first-stage candidates", finalEvidence: "final results", candidateToFinal: "Candidate-to-final ordering", candidate: "Candidate", firstRank: "First-stage rank", firstScore: "First-stage score", rerankerScore: "Cross-encoder score", finalRank: "Final rank", movement: "Movement", rerankOutcomes: { moved_up: "Moved up", moved_down: "Moved down", stayed: "Stayed", dropped: "Dropped" },
    vectorDbChecking: "Checking the optional local Qdrant service…", numpyRole: "The inspectable source of chunks and vectors.", qdrantRole: "An operational index for the same vectors, payloads, and filters.", sameRetrievalFlowTitle: "The retrieval flow does not change. ", sameRetrievalFlow: "The query is embedded once, searched against the same vectors, ranked by cosine similarity, and returned as evidence. Only vector storage and lookup move behind a different backend.", numpyMetadataSource: "NumPy has no database payload object. Its equivalent path, title, and chunk metadata come from the local chunk records.", qdrantPayloadSource: "Qdrant stores the same learner-facing metadata beside each vector as a database payload.", qdrantNotRunning: "Qdrant is not running", qdrantOptional: "The rest of the Retrieval course still works. Start the optional service when you want to compare index backends.", qdrantReadyToPrepare: "Qdrant is ready", qdrantCopyExact: "Prepare a verified collection by copying the bundled chunks and vectors—without re-chunking or re-embedding.", qdrantPrepare: "Prepare teaching collection", qdrantPreparing: "Copying and verifying vectors…", qdrantPreparedState: "The prepared collection is verified and reusable. Run the check again to see the idempotent reuse path.", qdrantVerifyAgain: "Verify prepared collection again", vectorPointCount: "Vector points", vectorDimension: "Vector dimension", vectorPoints: "points", payloadFilter: "Payload filter", payloadFilters: "Payload filters", filtersAvailable: "Available", filtersUnavailable: "Unavailable", legacyFiltersUnavailable: "This older Qdrant index remains searchable, but its minimal payload does not support source-group filters.", noFilter: "No filter · parity experiment", compareBackends: "Compare exact search", comparing: "Comparing…", parityMatch: "Exact-search parity verified", parityMismatch: "The backend rankings differ", parityTolerance: "Score tolerance:", filteredResults: "Separate filter demonstration", filterSeparate: "Filtering changes the candidate set, so this result is not labeled as NumPy/Qdrant parity.", storedPayload: "Inspect stored payload",
    buildViews: { build: "Build index", inspect: "Inspect index" },
    upload: "Add Markdown or text files", build: "Build index", question: "Ask a question", retrieve: "Retrieve", retrieving: "Retrieving…", ask: "Live ask", testing: "Testing connection…", generating: "Generating answer…", testConnection: "Test connection",
    noIndex: "Choose an index to begin exploring.",
    stages: ["Corpus", "Chunks", "Embeddings", "Retrieve", "Context", "Answer"],
    whatToNotice: "What to notice",
    learnStageFocus: [
      "Start with scope: this is the corpus and index behind the lesson.",
      "A document becomes several retrievable chunks; compare their source and text.",
      "These values are coordinates, not words. Search compares their direction and distance.",
      "Inspect the ranked candidates: related text is not always useful evidence.",
      "Compare selected and omitted chunks. Only selected evidence reaches the prompt.",
      "Read the answer with its cited sources, then match each citation to the evidence below.",
    ],
    evidence: "Evidence", prompt: "Grounded prompt", answer: "Answer", vectors: "Vector preview", manifest: "Index manifest",
    provider: "Live ask needs an OpenAI-compatible provider configured for this local lab.", providerTestHint: "Verifies this provider before it is used for Live ask.", providerUnlocked: "Live ask is unlocked by your verified provider connection.", generationFailed: "Live generation failed. Check provider settings and try again.", selectedEvidence: "Selected context evidence", generationRetrievalAudit: "Retrieval path used for generation", generationRetrievalAuditHint: "This candidate-to-final audit produced the evidence below. Only the selected evidence is packed into the generation prompt.", rerankingQuestionHint: "Choose a reviewed reranking example from the suggestions, or type your own question.", abstention: "Grounded abstention", noSupportedAnswer: "No supported answer in this corpus", abstained: "This question is outside the selected corpus’s coverage. The model found no support in its context, so it declined to invent an answer.", showFull: "Show full text", scenarioQuestion: "Question",
    quick: "Follow one complete, recorded RAG lesson first. Then use Explore to run your own retrievals over the same real corpus.",
    replay: "Start guided lesson", watson: "Download watsonxDocsQA", backend: "Vector index backend", index: "Index",
    providerUrl: "Provider API URL", providerModel: "Model", providerKey: "API key (this session only)", providerKeyConfigured: "•••••••• (from .env)", providerKeyFromEnvHint: "An API key is already configured via .env — leave this blank to use it, or enter one to override for this session.",
    modelReady: "Ready locally · 384 dimensions", modelMissing: "Not available locally. Download it to build indexes and run Dense or Hybrid retrieval.", modelDownloadRequired: "Dense and Hybrid retrieval need the default embedding model. Open Settings, download it, then retry.", modelDownloading: "Downloading embedding model…", modelDownloadInProgress: "Download in progress. This page will update when the model is ready.", downloadModel: "Download embedding model", rerankerSettings: "Pinned reranker model", rerankerReady: "Ready locally · cross-encoder reranking is available", rerankerMissing: "Not available locally. Download it to inspect or use cross-encoder reranking.", rerankerDownloading: "Downloading reranker model…", downloadReranker: "Download reranker model", pinnedRevision: "Pinned revision",
    retriever: "Retriever", topK: "Final top-k", reranker: "Reranker", noReranker: "None", crossEncoder: "Cross-encoder", candidateDepth: "Candidate depth", rerankerDownloadRequired: "Cross-encoder reranking needs the pinned local reranker model. Its download control is provided in Settings.", contextBudget: "Context budget (0 = unlimited)",
    selected: "Selected for context", omitted: "Not selected for context", vector: "Query vector", timings: "Stage timings",
    baseline: "Baseline", intervention: "Intervention", learn: "Read the learning guide", raw: "Inspect raw artifact", source: "Source", score: "Score", chunkReference: "Chunk ID", citationReference: "Source reference",
    scoreDetails: "Score details", citations: "Sources cited in the answer", indexFacts: "Index facts", chunks: "Chunks", documents: "Documents", embeddingModel: "Embedding model",
    buildIntro: "Start with a bundled corpus or bring a small corpus of your own. Then choose a local vector backend and build an inspectable index.",
    inspectIntro: "Review the saved index facts, chunks, and a numeric vector preview without leaving the lab.",
    exploreIntro: "Run retrieval or a live grounded answer, then follow the same artifacts through each pipeline stage.",
    failureIntro: "Compare a known failure with an intervention using the project’s curated trace artifacts.",
    settingsIntro: "Check the two pinned local retrieval models and configure an optional OpenAI-compatible provider.",
    replayDetail: "Recorded offline lesson · no model download or provider required.",
    buildPath: "Build a small index", buildPathDetail: "Upload a small corpus, inspect its chunks, then ask your own question.",
    rawVector: "First 8 dimensions only — these values are a numeric preview, not human-readable concepts.",
    bundledCorpus: "Use a bundled corpus", customCorpus: "Bring a small corpus", chooseUploadedCorpus: "Choose an uploaded corpus", noUploadedCorpus: "No uploaded corpus yet", or: "or",
    qdrantReady: "Qdrant — ready", qdrantUnavailable: "Qdrant — unavailable", qdrantUnavailableHint: "Start the optional Qdrant service to use this backend.", embeddingSettings: "Pinned embedding model", embeddingModelRole: "Required for Dense and Hybrid retrieval, query vectors, and vector index building.", rerankerModelRole: "Additionally required only when cross-encoder reranking is selected.", cpuModelRuntime: "Both models run locally on CPU. No GPU, CUDA, or NVIDIA runtime is required.", providerSettings: "OpenAI-compatible provider", runConfiguration: "Run configuration",
    corpusAdded: "Corpus added.", indexing: "Indexing locally…", indexReady: "Index ready.", watsonStatus: "watsonxDocsQA", myCorpus: "My corpus",
    retrieverOptions: { dense: "Dense", bm25: "BM25", hybrid: "Hybrid (RRF)" },
    learnIntro: "Follow a saved lesson over pinned technical documentation. Each step exposes the actual artifact the RAG system used.", lesson: "Guided lesson", recorded: "Saved teaching result — no live model call", continueLesson: "Continue", loadingLesson: "Loading lesson…", expectedSources: "Expected", retrievedSources: "Retrieved", catalogQuestion: "Catalog question", freeQuestion: "Free question", goldCheck: "Gold-source check", hit: "A gold source was retrieved", miss: "No gold source was retrieved", sourceIdentity: "Pinned source identity",
  },
  zh: {
    title: "tiny-rag-lab",
    subtitle: "循序看见经典 RAG 如何工作。",
    areas: { home: "主页", learn: "学习", retrieval: "检索", build: "构建与检查", explore: "探索", failure: "失败实验室", settings: "设置" } satisfies Record<Area, string>,
    retrievalIntro: "沿着一次实时检索，从词语、向量、融合、重排一路走到评估；无需配置大语言模型服务。",
    retrievalModules: {
      lexical: { title: "词法检索", description: "哪些查询词贡献了这个 BM25 分数？" },
      dense: { title: "语义检索", description: "向量如何得到余弦相似度？" },
      "vector-db": { title: "向量数据库", description: "把同一批向量从 NumPy 移到 Qdrant。" },
      hybrid: { title: "混合检索", description: "使用 RRF 融合词法和语义排名。" },
      reranking: { title: "重排", description: "把较大的候选集重新排序为最终相关结果。" },
      evaluation: { title: "评估", description: "用 16 个问题比较两种检索配置。" },
    },
    curatedQuestion: "评审过的问题", reviewedSources: "评审过的标准来源文档", runLesson: "运行实时检索", runningLesson: "正在检索并解释…", questionTokens: "查询词元", termContributions: "BM25 词项贡献", vectorMath: "余弦计算", vectorReadingGuide: "从零线开始读图：蓝色正值向上延伸，珊瑚色负值向下延伸；长度表示该数值在当前向量预览中的相对幅度。", candidateVector: "分块向量", queryNorm: "查询向量范数", chunkNorm: "分块向量范数", dotProduct: "点积", cosine: "余弦相似度", formula: "计算过程", courseUnavailable: "评审过的检索课程材料尚未安装。", moduleComing: "这个实时模块将在当前里程碑的下一个任务中实现。", exactArtifacts: "以下数值来自实际产生本次排名的同一套引擎计算。",
    bm25Meaning: "BM25 会把每个查询词项的贡献相加。某个词既出现在当前分块、又在整个语料中较少见时，它更重要；长度归一化则避免长分块仅仅因为词更多就胜出。",
    bm25Formula: "分数 = Σ 查询次数 × IDF × tf(k1 + 1) / (tf + k1(1 − b + b × dl / avgdl))",
    bm25Columns: { term: "查询词项", queryCount: "查询中出现次数", termFrequency: "分块内出现次数", documentFrequency: "包含该词的分块数", inverseDocumentFrequency: "逆文档频率", contribution: "分数贡献", documentLength: "分块长度", averageDocumentLength: "平均分块长度" },
    rrfFormula: "每个来源贡献 1 / ({k} + 排名)，融合分数是所有贡献之和。", rrfMissingSource: "若分块不在某个来源的候选列表中，该来源贡献为 0。", notInSourceRanking: "不在此来源的候选列表中", denseRanking: "语义检索排名", lexicalRanking: "BM25 排名", fusedRanking: "融合后排名", firstStageCandidates: "个第一阶段候选", finalEvidence: "个最终结果", candidateToFinal: "候选到最终结果的排序变化", candidate: "候选", firstRank: "第一阶段排名", firstScore: "第一阶段分数", rerankerScore: "交叉编码器分数", finalRank: "最终排名", movement: "变化", rerankOutcomes: { moved_up: "上升", moved_down: "下降", stayed: "不变", dropped: "丢弃" },
    vectorDbChecking: "正在检查可选的本地 Qdrant 服务……", numpyRole: "可直接检查的分块和向量来源。", qdrantRole: "为同一批向量提供工程化索引、载荷与过滤。", sameRetrievalFlowTitle: "检索流程不会改变。", sameRetrievalFlow: "查询只嵌入一次，再对同一批向量执行搜索，按余弦相似度排序并返回为证据；只有向量的存储和查找交给了不同后端。", numpyMetadataSource: "NumPy 没有数据库载荷对象；等价的路径、标题和分块元数据来自本地分块记录。", qdrantPayloadSource: "Qdrant 把同样的学习用元数据作为数据库载荷，和每个向量存放在一起。", qdrantNotRunning: "Qdrant 尚未运行", qdrantOptional: "检索课程的其他内容仍可使用。需要比较索引后端时，再启动可选服务。", qdrantReadyToPrepare: "Qdrant 已就绪", qdrantCopyExact: "复制随附索引中的分块和向量，完成验证后建立课程集合；不会重新分块或重新嵌入。", qdrantPrepare: "准备课程集合", qdrantPreparing: "正在复制并验证向量……", qdrantPreparedState: "课程集合已经验证并可以复用。再次检查可观察幂等复用路径。", qdrantVerifyAgain: "再次验证已准备的集合", vectorPointCount: "向量点数", vectorDimension: "向量维度", vectorPoints: "个向量点", payloadFilter: "载荷过滤", payloadFilters: "载荷过滤", filtersAvailable: "可用", filtersUnavailable: "不可用", legacyFiltersUnavailable: "这个旧版 Qdrant 索引仍可检索，但其精简载荷不支持来源分组过滤。", noFilter: "不过滤 · 一致性实验", compareBackends: "比较精确检索", comparing: "正在比较……", parityMatch: "已验证精确检索一致性", parityMismatch: "两个后端的排名不同", parityTolerance: "分数容差：", filteredResults: "独立的过滤演示", filterSeparate: "过滤会改变候选集合，因此这里不会标记为 NumPy/Qdrant 一致性结果。", storedPayload: "检查存储的载荷",
    buildViews: { build: "构建索引", inspect: "检查索引" },
    upload: "添加 Markdown 或文本文件", build: "构建索引", question: "输入问题", retrieve: "检索", retrieving: "正在检索…", ask: "实时问答", testing: "正在测试连接…", generating: "正在生成答案…", testConnection: "测试连接",
    noIndex: "选择一个索引后即可开始探索。",
    stages: ["语料", "分块", "嵌入", "检索", "上下文", "答案"],
    whatToNotice: "观察重点",
    learnStageFocus: [
      "先确认范围：这是本课程使用的语料与索引。",
      "一篇文档会变成多个可检索分块；对比它们的来源与文本。",
      "这些数值是坐标，不是词语；搜索比较的是它们的方向与距离。",
      "检查排序后的候选：相关文本不一定是有用的证据。",
      "对比选入与未选入的分块；只有选入的证据会进入提示词。",
      "将答案与其引用来源一起阅读，再把每条引用对应到下方证据。",
    ],
    evidence: "证据", prompt: "基于证据的提示词", answer: "答案", vectors: "向量预览", manifest: "索引清单",
    provider: "实时问答需要为本地实验室配置 OpenAI 兼容的模型服务。", providerTestHint: "先验证模型服务，才能用于实时问答。", providerUnlocked: "已验证的模型服务已解锁实时问答。", generationFailed: "实时生成失败。请检查模型服务设置后重试。", selectedEvidence: "选入上下文的证据", generationRetrievalAudit: "生成实际使用的检索路径", generationRetrievalAuditHint: "这份候选到最终结果的记录生成了下方证据；只有被选中的证据会装入生成提示词。", rerankingQuestionHint: "可从建议中选择一道评审过的重排问题，也可以直接输入自己的问题。", abstention: "基于证据的拒答", noSupportedAnswer: "当前语料中没有可支持的答案", abstained: "这个问题超出了当前所选语料的覆盖范围。模型在上下文中找不到支持证据，因此拒绝编造答案。", showFull: "展开完整文本", scenarioQuestion: "问题",
    quick: "先沿着一次完整、已记录的 RAG 课程学习，再用探索页在同一真实语料上运行自己的检索。",
    replay: "开始引导课程", watson: "下载 watsonxDocsQA", backend: "向量索引后端", index: "索引",
    providerUrl: "模型服务 API 地址", providerModel: "模型", providerKey: "API 密钥（仅当前会话）", providerKeyConfigured: "••••••••（来自 .env）", providerKeyFromEnvHint: "已通过 .env 配置 API 密钥——留空即可使用，或输入一个密钥以覆盖当前会话。",
    modelReady: "已在本地就绪 · 384 维", modelMissing: "本地尚未提供。下载后即可构建索引并运行语义或混合检索。", modelDownloadRequired: "语义检索和混合检索需要默认嵌入模型。请前往设置下载模型后重试。", modelDownloading: "正在下载嵌入模型…", modelDownloadInProgress: "下载正在进行中。模型就绪后此页面会自动更新。", downloadModel: "下载嵌入模型", rerankerSettings: "固定版本的重排模型", rerankerReady: "已在本地就绪 · 可以使用交叉编码器重排", rerankerMissing: "本地尚未提供。下载后即可检查或使用交叉编码器重排。", rerankerDownloading: "正在下载重排模型…", downloadReranker: "下载重排模型", pinnedRevision: "固定版本",
    retriever: "检索器", topK: "最终 Top-k", reranker: "重排器", noReranker: "不使用", crossEncoder: "交叉编码器", candidateDepth: "候选深度", rerankerDownloadRequired: "交叉编码器重排需要固定版本的本地重排模型；可在设置页使用对应下载控件。", contextBudget: "上下文预算（0 = 不限）", selected: "已选入上下文", omitted: "未选入上下文", vector: "查询向量", timings: "阶段耗时",
    baseline: "基线", intervention: "干预", learn: "阅读学习指南", raw: "查看原始产物", source: "来源", score: "分数", chunkReference: "分块 ID", citationReference: "来源引用",
    scoreDetails: "分数详情", citations: "答案引用的来源", indexFacts: "索引事实", chunks: "分块", documents: "文档", embeddingModel: "嵌入模型",
    buildIntro: "使用随附的语料库，或带入自己的小型语料库。接着选择本地向量后端，并构建可检查的索引。",
    inspectIntro: "无需离开实验室，即可检查已保存的索引事实、分块和数值化向量预览。",
    exploreIntro: "运行检索或实时的基于证据问答，并沿着每个管道阶段查看同一批产物。",
    failureIntro: "使用项目精心设计的 trace 产物，对比一个已知失败案例和干预措施。",
    settingsIntro: "检查两种固定版本的本地检索模型，并配置可选的 OpenAI 兼容模型服务。",
    replayDetail: "已记录的离线课程 · 无需下载模型或配置模型服务。",
    buildPath: "构建小型索引", buildPathDetail: "上传一个小型语料库，检查它的分块，再提出自己的问题。",
    rawVector: "仅显示前 8 个维度——这些数值是预览，不对应人类可读的概念。",
    bundledCorpus: "使用随附的语料库", customCorpus: "带入小型语料库", chooseUploadedCorpus: "选择已上传的语料库", noUploadedCorpus: "尚未上传语料库", or: "或",
    qdrantReady: "Qdrant — 已就绪", qdrantUnavailable: "Qdrant — 不可用", qdrantUnavailableHint: "启动可选的 Qdrant 服务后即可使用此后端。", embeddingSettings: "固定版本的嵌入模型", embeddingModelRole: "语义检索、混合检索、查询向量和构建向量索引需要此模型。", rerankerModelRole: "只有选择交叉编码器重排时，才额外需要此模型。", cpuModelRuntime: "两个模型都在本地 CPU 上运行，不需要 GPU、CUDA 或 NVIDIA 运行时。", providerSettings: "OpenAI 兼容模型服务", runConfiguration: "运行配置",
    corpusAdded: "已添加语料库。", indexing: "正在本地构建索引…", indexReady: "索引已就绪。", watsonStatus: "watsonxDocsQA", myCorpus: "我的语料库",
    retrieverOptions: { dense: "语义检索", bm25: "BM25", hybrid: "混合（RRF）" },
    learnIntro: "沿着一条固定技术文档上的已保存课程学习。每一步都展示 RAG 系统实际使用的产物。", lesson: "引导课程", recorded: "保存的教学结果——未调用实时模型", continueLesson: "继续", loadingLesson: "正在加载课程…", expectedSources: "标准来源", retrievedSources: "检索到的来源", catalogQuestion: "题库问题", freeQuestion: "自由问题", goldCheck: "标准来源检查", hit: "已检索到标准来源", miss: "未检索到标准来源", sourceIdentity: "固定来源标识",
  },
} as const;

export type Copy = (typeof copy)[Lang];

export function learningMaterialUrl(lang: Lang, page: string) {
  return `/docs/${lang}/${page.replace(/\.md$/, ".html")}`;
}
