import type { Copy } from "../copy";

export function SettingsView({ modelReady, downloadingModel, providerUrl, providerModel, providerKey, providerReady, testing, generating, onDownload, onTest, onProviderUrl, onProviderModel, onProviderKey, t }: {
  modelReady: boolean | null; downloadingModel: boolean; providerUrl: string; providerModel: string; providerKey: string; providerReady: boolean; testing: boolean; generating: boolean; onDownload: () => void; onTest: () => void; onProviderUrl: (value: string) => void; onProviderModel: (value: string) => void; onProviderKey: (value: string) => void; t: Copy;
}) {
  const providerControlsLocked = testing || generating;
  return <section className="view" aria-labelledby="settings-title"><span className="kicker">{t.areas.settings}</span><h2 id="settings-title">{t.areas.settings}</h2><p className="lead">{t.settingsIntro}</p>
    <section className="section-block"><h3>{t.embeddingSettings}</h3><p className="hint">{modelReady ? <><strong>all-MiniLM-L6-v2</strong> · 384 dimensions · ready locally</> : downloadingModel ? t.modelDownloadInProgress : t.modelMissing}</p>{!modelReady && <button type="button" className="primary-action" disabled={downloadingModel} onClick={onDownload}>{downloadingModel ? t.modelDownloading : t.downloadModel}</button>}</section>
    <section className="section-block"><h3>{t.providerSettings}</h3><div className="settings-fields"><label>{t.providerUrl}<input disabled={providerControlsLocked} value={providerUrl} onChange={(event) => onProviderUrl(event.target.value)} placeholder="https://provider.example/v1 or …/v1/chat/completions" /></label><label>{t.providerModel}<input disabled={providerControlsLocked} value={providerModel} onChange={(event) => onProviderModel(event.target.value)} placeholder="model-name" /></label><label>{t.providerKey}<input disabled={providerControlsLocked} type="password" value={providerKey} onChange={(event) => onProviderKey(event.target.value)} /></label></div>{!providerReady && <p className="hint">{t.provider}</p>}<button type="button" disabled={!providerReady || providerControlsLocked} onClick={onTest}>{testing ? t.testing : t.testConnection}</button><p className="hint">{t.providerTestHint}</p></section>
  </section>;
}
