import type { Copy } from "../copy";

export function SettingsView({ modelReady, downloadingModel, rerankerReady, downloadingReranker, providerUrl, providerModel, providerKey, environmentKeyConfigured, providerReady, testing, generating, onDownload, onDownloadReranker, onTest, onProviderUrl, onProviderModel, onProviderKey, t }: {
  modelReady: boolean | null; downloadingModel: boolean; rerankerReady: boolean | null; downloadingReranker: boolean; providerUrl: string; providerModel: string; providerKey: string; environmentKeyConfigured: boolean; providerReady: boolean; testing: boolean; generating: boolean; onDownload: () => void; onDownloadReranker: () => void; onTest: () => void; onProviderUrl: (value: string) => void; onProviderModel: (value: string) => void; onProviderKey: (value: string) => void; t: Copy;
}) {
  const showKeyFromEnvHint = environmentKeyConfigured && !providerKey;
  const providerControlsLocked = testing || generating;
  const modelDownloadLocked = downloadingModel || downloadingReranker;
  return <section className="view" aria-labelledby="settings-title"><span className="kicker">{t.areas.settings}</span><h2 id="settings-title">{t.areas.settings}</h2><p className="lead">{t.settingsIntro}</p>
    <div className="settings-models"><ModelSetting title={t.embeddingSettings} role={t.embeddingModelRole} model="sentence-transformers/all-MiniLM-L6-v2" revision="1110a243fdf4706b3f48f1d95db1a4f5529b4d41" ready={modelReady} downloading={downloadingModel} locked={modelDownloadLocked} readyText={t.modelReady} missingText={t.modelMissing} downloadText={t.downloadModel} downloadingText={t.modelDownloading} revisionLabel={t.pinnedRevision} onDownload={onDownload} /><ModelSetting title={t.rerankerSettings} role={t.rerankerModelRole} model="cross-encoder/ms-marco-MiniLM-L-6-v2" revision="c5ee24cb16019beea0893ab7796b1df96625c6b8" ready={rerankerReady} downloading={downloadingReranker} locked={modelDownloadLocked} readyText={t.rerankerReady} missingText={t.rerankerMissing} downloadText={t.downloadReranker} downloadingText={t.rerankerDownloading} revisionLabel={t.pinnedRevision} onDownload={onDownloadReranker} /></div>
    <p className="model-runtime-note">{t.cpuModelRuntime}</p>
    <section className="section-block"><h3>{t.providerSettings}</h3><div className="settings-fields"><label>{t.providerUrl}<input disabled={providerControlsLocked} value={providerUrl} onChange={(event) => onProviderUrl(event.target.value)} placeholder="https://provider.example/v1 or …/v1/chat/completions" /></label><label>{t.providerModel}<input disabled={providerControlsLocked} value={providerModel} onChange={(event) => onProviderModel(event.target.value)} placeholder="model-name" /></label><label>{t.providerKey}<input disabled={providerControlsLocked} type="password" value={providerKey} onChange={(event) => onProviderKey(event.target.value)} placeholder={environmentKeyConfigured ? t.providerKeyConfigured : undefined} /></label></div>{showKeyFromEnvHint && <p className="hint">{t.providerKeyFromEnvHint}</p>}{!providerReady && <p className="hint">{t.provider}</p>}<button type="button" disabled={!providerReady || providerControlsLocked} onClick={onTest}>{testing ? t.testing : t.testConnection}</button><p className="hint">{t.providerTestHint}</p></section>
  </section>;
}

function ModelSetting({ title, role, model, revision, ready, downloading, locked, readyText, missingText, downloadText, downloadingText, revisionLabel, onDownload }: { title: string; role: string; model: string; revision: string; ready: boolean | null; downloading: boolean; locked: boolean; readyText: string; missingText: string; downloadText: string; downloadingText: string; revisionLabel: string; onDownload: () => void }) {
  return <section className="section-block model-setting"><h3>{title}</h3><p className="model-role">{role}</p><strong className="model-name">{model}</strong><code>{revisionLabel}: {revision.slice(0, 12)}…</code><p className={`hint model-readiness ${ready ? "ready" : "missing"}`}>{ready ? readyText : downloading ? downloadingText : missingText}</p>{!ready && <button type="button" className="primary-action" disabled={locked} onClick={onDownload}>{downloading ? downloadingText : downloadText}</button>}</section>;
}
